classDiagram
    direction LR

    class دانشجو {
        +شماره_دانشجویی : String
        +نام : String
        +ایمیل : String
        +لیست_درخواست‌ها()
        +ارسال_درخواست(نوع، شرکت)
    }

    class استاد_راهنما {
        +کد_استادی : String
        +نام : String
        +تعداد_ظرفیت : Int
        +بررسی_درخواست(درخواست)
        +تایید_یا_رد(درخواست, وضعیت)
    }

    class مدیر_آموزش {
        +کد_کاربری : String
        +نام : String
        +تأیید_نهایی_درخواست(درخواست)
    }

    class درخواست_کارآموزی {
        +شناسه_درخواست : Int
        +تاریخ_ارسال : Date
        +نوع_کارآموزی : String
        +وضعیت : State
        +محل_شرکت : String
        +ارزیابی_نهایی : String
        +مشاهده_جزئیات()
    }

    دانشجو "1" --> "0..*" درخواست_کارآموزی : ثبت می‌کند
    استاد_راهنما "1" --> "0..*" درخواست_کارآموزی : بازبینی می‌کند
    مدیر_آموزش "1" --> "0..*" درخواست_کارآموزی : تأیید نهایی می‌کند
    درخواست_کارآموزی "0..*" --> "1" استاد_راهنما : ارجاع به
    
    State درخواست_کارآموزی.وضعیت {
        Submitted
        ApprovedBySupervisor
        FinalReview
        Approved
        Rejected
    }
