flowchart LR

%% ================= Actors =================
student(["👤 دانشجو"])
advisor(["👤 استاد راهنما"])
industry(["👤 مسئول واحد صنعتی"])
admin(["👤 مدیر سامانه"])

%% ============== System Boundary ==============
subgraph System["سامانه ثبت کارآموزی دانشجویان"]
    UC_Register("⭑ ثبت‌نام کارآموزی")
    UC_UploadDocs("⭑ بارگذاری مدارک")
    UC_TrackStatus("⭑ پیگیری وضعیت درخواست")
    UC_AdvisorApprove("⭑ تایید استاد راهنما")
    UC_AdvisorReject("⭑ رد درخواست توسط استاد راهنما")
    UC_IndustryApprove("⭑ تایید محل کارآموزی")
    UC_AdminManageUsers("⭑ مدیریت کاربران")
    UC_AdminManageInterns("⭑ مدیریت درخواست‌های کارآموزی")
end

%% =============== Associations ===============
student --- UC_Register
student --- UC_UploadDocs
student --- UC_TrackStatus

advisor --- UC_AdvisorApprove
advisor --- UC_AdvisorReject

industry --- UC_IndustryApprove

admin --- UC_AdminManageUsers
admin --- UC_AdminManageInterns

class K company;
class M teacher
